# Generated by Django 5.1.5 on 2025-01-29 04:50

import users_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60, validators=[users_app.validators.validate_name_format])),
                ('last_name', models.CharField(default=None, max_length=60, validators=[users_app.validators.validate_name_format])),
                ('email', models.CharField(max_length=100, unique=True, validators=[users_app.validators.validate_email])),
            ],
        ),
    ]
