services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    #restart: always
    depends_on:
      - db
  app:
    # Image to use
    image: python:3.12
    # Working directory inside the container
    working_dir: /app
    ports:
      # Map port inside container to port 8000 on host
      - "8000:8000"
    volumes:
      # Allows for syncing files for updating during development
      - .:/app
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=craig_db
    ports:
      - '5454:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: